### ISSUE TITLE
[Question] How to train a model with a one liner?

### ISSUE THREAD

**Issue by MartinaRuocco** [ARISE-Initiative/robosuite#105]
Hi!
Is there a way to train a model with a one-liner using [Stable Baselines](https://github.com/hill-a/stable-baselines) or [Openai Baselines](https://github.com/openai/baselines/)?

**Comment by yukezhu** [comment]
Hi please check out https://github.com/ARISE-Initiative/robosuite-benchmark for our new benchmarking results on our v1.0 release. Thanks.
