### ISSUE TITLE
Using `pip install robosuite` results in some missing folders after installation

### ISSUE THREAD

**Issue by hermanjakobsen** [ARISE-Initiative/robosuite#111]
After using `pip install robosuite` the `controllers/interpolators/` folder is missing. A solution to the problem might be to update the `MANIFEST.in` file as pointed out here (https://stackoverflow.com/questions/10847764/after-installation-of-python-package-from-git-repository-some-folders-are-missin)

**Comment by yukezhu** [comment]
Thanks for bringing this up! We have fixed this packaging issue and updated it on PyPI. I closed this issue for now, but please let us know if there's any further problem.
