### ISSUE TITLE
Adding new papers using robosuite

### ISSUE THREAD

**Issue by yukezhu** [ARISE-Initiative/robosuite#118]
"Variational Imitation Learning with Diverse-quality Demonstrations" Voot Tangkaratt, Bo Han, Mohammad Emtiyaz Khan, Masashi Sugiyama, ICML 2020. https://proceedings.icml.cc/static/paper_files/icml/2020/577-Paper.pdf

**Comment by yukezhu** [comment]
"Conservative Safety Critics for Exploration" Homanga Bharadhwaj, Aviral Kumar, Nicholas Rhinehart, Sergey Levine, Florian Shkurti, Animesh Garg. https://arxiv.org/abs/2010.14497

**Comment by yukezhu** [comment]
"Transformers for One-Shot Visual Imitation" Sudeep Dasari, Abhinav Gupta. https://corlconf.github.io/paper_463/

**Comment by yukezhu** [comment]
"Deep Reinforcement Learning for Contact-Rich Skills Using Compliant Movement Primitives" Oren Spector, Miriam Zacksenhouse. https://arxiv.org/abs/2008.13223

**Comment by cremebrule** [comment]
fixed in #137
