### ISSUE TITLE
[Question] How to render contact forces? 

### ISSUE THREAD

**Issue by hermanjakobsen** [ARISE-Initiative/robosuite#121]
Hi! 
As to my understanding, `mujoco-py` already has implemented the possibility of rendering the contact forces in the `MjViewer` [class](https://openai.github.io/mujoco-py/build/html/reference.html) by pressing "C" on the keyboard while rendering a simulation. However, when I press "C" during a simulation nothing happens. I have tried to render the simulation with both `env.render()` and with `MjViewer.sim()`.
Are you guys able to render the contact forces?

**Comment by cremebrule** [comment]
Hi @hermanjakobsen ,

Thanks for bringing up this issue -- I verified on my local machine (MacOS) that I too cannot render the contact forces. I checked using an old version of the repo with Mujoco 1.50 and it works fine there, so I'm wondering if it's a mujoco version related issue.

I saw you posted this same issue on the main mujoco-py repo, which is great! Would be great to keep us updated on that end as well. Hopefully there is a quick fix for this, as contact forces are very nice for debugging / visualization.
