### ISSUE TITLE
Agentview camera position adjustment

### ISSUE THREAD

**Issue by yukezhu** [ARISE-Initiative/robosuite#123]
Improve agentview camera positions for the following tasks:

Door
![image](https://user-images.githubusercontent.com/1192449/98774454-a1c21700-23b0-11eb-8890-cc2906fda0bf.png)

TwoArmPegInHole
![image](https://user-images.githubusercontent.com/1192449/98774239-3710db80-23b0-11eb-9f52-c98afa2d6ec2.png)

TwoArmHandover
![image](https://user-images.githubusercontent.com/1192449/98774372-7fc89480-23b0-11eb-9861-5bc8347b664e.png)

**Comment by cremebrule** [comment]
fixed in #137
