### ISSUE TITLE
[Question] Is it possible to change the model parameters on the fly? 

### ISSUE THREAD

**Issue by hermanjakobsen** [ARISE-Initiative/robosuite#126]
Hi guys! 

I was wondering if it is possible to change model parameters on the fly (e.g. body_mass)? 
I have checked out this [issue](https://github.com/openai/gym/issues/234), and it looks like to be a version related problem with mujoco-py. Do you guys happen to know about any workarounds? 

The use case is to change the constraint parameters `solrefsmooth` and `solimpsmooth` of my composite object (soft body) between training episodes/simulations in order to mimic the softness variations of different human bodies.

**Comment by amandlek** [comment]
As mentioned in the issue you linked - this is straightforward as long as you would like to do this between episodes. For every new episode, the model xml is programmatically generated and used to create a new simulation instance. Thus, to change model parameters between episodes, we make sure there is corresponding logic when creating the xml. For example, we randomize the size of the cube in our Lift task - take a look [here](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/lift.py#L309). You can do something similar depending on how your are creating the composite object - if you are loading it from a separate XML, you can do something similar to [here](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/objects/xml_objects.py#L157).
