### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by zilmano** [ARISE-Initiative/robosuite#127]
There is a discrepancy between an argument name in the docs and the code:
At **https://robosuite.ai/docs/modules/controllers.html#Loading-a-Controller**
the doc specifies "controller_config" for the make function:
**env = suite.make("Lift", robots="Panda", controller_config=config, ... )**
Running like in the example gives an error as, for all environments, 
the argument name in the code is "controller_config**s**"

Just an FYI on this

**Comment by yukezhu** [comment]
Thanks for the report. This has been fixed, and will be updated to the documentations in the next few days.
