### ISSUE TITLE
Thanks for the work. Any plan for a pybullet port?

### ISSUE THREAD

**Issue by vincentzhang** [ARISE-Initiative/robosuite#145]
Does anyone know if a port to Pybullet is underway somewhere?

Thanks

**Comment by yukezhu** [comment]
You can find other efforts from us on pybullet-based robotics simulation (https://github.com/StanfordVL/robovat, http://svl.stanford.edu/igibson/). There's no plan to port robosuite to PyBullet from our ends. Though we welcome community contributors to do so if they are interested.
