### ISSUE TITLE
Error when adding multiple same class xml objects

### ISSUE THREAD

**Issue by ray8828** [ARISE-Initiative/robosuite#149]
Thanks for sharing this great job!

When I try to add multiple same class XML objects e.g. two BottelObject to an environment, I got an  mjcf XML error, (I've already specified different names for the objects)

Failed to load XML from string. mj_loadXML error: b'Error: repeated name in body array, position 25\nObject name = bottle_main, id = 25, line = 267, column = 7'

**Comment by cremebrule** [comment]
Thanks for catching this bug! This is fixed in the most recent PR.

**Comment by PraveenElango** [comment]
Hi, I am getting the same error now when I am creating a new BoxObject in the wipe_arena.py file with a new name.
