### ISSUE TITLE
"Bimanual: TypeError: concatenate() takes from 1 to 3 positional arguments but 9 were given", proposed fix

### ISSUE THREAD

**Issue by bebbo203** [ARISE-Initiative/robosuite#152]
When using a TwoArmEnv with a bimanual robot, the following error is shown:
`TypeError: concatenate() takes from 1 to 3 positional arguments but 9 were given`

As a possible solution, line 376 of "robots/bimanual.py" can be changed from: 
`di[pf + "robot-state"] = np.concatenate(di[pf + "robot-state"], *robot_states)`
to
`di[pf + "robot-state"] = np.concatenate([di[pf + "robot-state"], *robot_states])`

**Comment by yukezhu** [comment]
This is fixed. Thanks for the bug report!
