### ISSUE TITLE
Is the code using robosuite able to also be used to control the real Panda arm in Dr. Zhu's lab?

### ISSUE THREAD

**Issue by quinnliu** [ARISE-Initiative/robosuite#163]
Hi, 

I assume this is true but just want to confirm. 

Is the code using robosuite able to also be used to control the real Panda arm in Dr. Zhu's lab?

Thanks,
Q

**Comment by yukezhu** [comment]
Not exactly. We have another set of real robot infrastructure in C++. But the math behind the controllers in robosuite and tje real Panda arms is the same.
