### ISSUE TITLE
Anyone interested in coding the robot arms to build a wall of bricks for a home?

### ISSUE THREAD

**Issue by quinnliu** [ARISE-Initiative/robosuite#172]
Hi Dr. Zhu && Josiah && anyone interested in helping,

Not sure if this is okay to post here but I'm very very determined to build a real home using generally intelligent robotics but to first do so in a `robosuite` simulation using Panda arms. If this isn't okay feel free to close the issue :) 

Specifically I'm interested in coding a simulation using `robosuite` of a visual cognitive computer(VCC) from papers here:
1. https://vcrs.wpengine.com/wp-content/uploads/2020/03/10.1126@scirobotics.aav3150.pdf
2. https://vcrs.wpengine.com/wp-content/uploads/2020/03/behavior-is-everything-pdf.pdf
3. https://science.sciencemag.org/content/sci/358/6368/eaag2612.full.pdf

And then using the VCC to build a home out of bricks using their IKEA image training input strategy.

After we figure out how to lay the bricks in the `robosuite` simulation I plan to take it a lot further like windows, doors, plumbing, sink, toilet, shower... && then using the real Panda arm for building a tiny home at 1/12 scale && then at real home scale. 

But I think it's important to start small with a wall of bricks in simulation.

Best,
Q

**Comment by quinnliu** [comment]
I'm just getting started && this is my progress so far :) 

![Screen Shot 2021-01-13 at 8 34 04 PM](https://user-images.githubusercontent.com/2585159/104538007-b1dcb980-55e0-11eb-9f6f-bc9d07f26b62.png)

**Comment by yukezhu** [comment]
Hi @quinnliu This issues page is dedicated to bug reports and feature requests. You are welcome to discuss your ideas of using robosuite on other online platforms, but this is not the right place. Thanks.
