### ISSUE TITLE
Playback script does not reproduce deterministic results

### ISSUE THREAD

**Issue by zhuyifengzju** [ARISE-Initiative/robosuite#173]
Currently the scripts for playing back demonstrations seem to have a problem to reproduce the same trajectories as in the collected demonstrations. So if first collect data using:
`python scripts/collect_human_demonstrations.py --device spacemouse`, and then run  `python scripts/playback_demonstrations_from_hdf5.py --folder DEMONSTRATION_FOLDER --use-actions`, it will gives the following error:
`Traceback (most recent call last):
  File "scripts/playback_demonstrations_from_hdf5.py", line 93, in <module>
    assert(np.all(np.equal(states[j + 1], state_playback)))
AssertionError`

Seems like the deterministic playback is broken somehow.

**Comment by yukezhu** [comment]
Confirmed this issue on my end. Example [demo.hdf5](https://utexas.box.com/s/tjlnuec4e3xzjcoalkk9mq8odn3j3l5c)

State-only playback
![image](https://user-images.githubusercontent.com/1192449/104548186-e4dd7800-55f5-11eb-8b43-51926dc7a894.png)

Action playback
![image](https://user-images.githubusercontent.com/1192449/104548270-11918f80-55f6-11eb-8201-57d1ef60078d.png)

**Comment by yukezhu** [comment]
Also, playback script complained about missing `joint_torques` values in hdf5
https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/scripts/playback_demonstrations_from_hdf5.py#L83
