### ISSUE TITLE
Adding end effector's positional and rotational velocity as default observations?

### ISSUE THREAD

**Issue by zhuyifengzju** [ARISE-Initiative/robosuite#175]
I found that there is no default observations on end effector's velocities. Should we add such them as default?

**Comment by yukezhu** [comment]
@zhuyifengzju did you find that the end-effector's velocities useful in any of your learning tasks? It can be easily added to the `observables` from here: https://github.com/ARISE-Initiative/robosuite/blob/779a3b7c91e8faab4a4f1285acae3e8c9b63faaf/robosuite/robots/single_arm.py#L316

**Comment by zhuyifengzju** [comment]
Currently I am not using any velocity information in my tasks. Yeah I realize it's easier to add a sensor observation in an environment. We can close this issue now.
