### ISSUE TITLE
About weird behaviors for cylinder object in stack env

### ISSUE THREAD

**Issue by YunchuZhang** [ARISE-Initiative/robosuite#187]
Hi there,
I just try to change the cube object to cylinder like this in staking environment :
<img width="587" alt="Screen Shot 2021-02-10 at 1 09 03 AM" src="https://user-images.githubusercontent.com/33641269/107472229-9233a500-6b3c-11eb-9d2d-77b6356652cc.png">
But after that, the cylinder keep weird actions itself without any contact with gripper like rotate itself, and jump down to the floor:
<img width="960" alt="Screen Shot 2021-02-10 at 1 06 14 AM" src="https://user-images.githubusercontent.com/33641269/107472355-cf983280-6b3c-11eb-8e63-727c38e65279.png">
<img width="832" alt="Screen Shot 2021-02-10 at 1 05 32 AM" src="https://user-images.githubusercontent.com/33641269/107472363-d0c95f80-6b3c-11eb-9bb3-33fe86ed1e26.png">
<img width="549" alt="Screen Shot 2021-02-10 at 1 07 05 AM" src="https://user-images.githubusercontent.com/33641269/107472371-d32bb980-6b3c-11eb-888c-16738b49110f.png">
<img width="475" alt="Screen Shot 2021-02-10 at 1 07 09 AM" src="https://user-images.githubusercontent.com/33641269/107472373-d3c45000-6b3c-11eb-80b0-a6dcff683713.png">

Do you know why this happened? Thanks

**Comment by zhuyifengzju** [comment]
Have you defined the  sampler properly for the cylinder (both position and orientation, z_offset etc.)?

**Comment by YunchuZhang** [comment]
<img width="756" alt="Screen Shot 2021-02-10 at 1 50 22 AM" src="https://user-images.githubusercontent.com/33641269/107475570-57cd0680-6b42-11eb-9d5f-be51e6a54b58.png">
do you mean this? I did not change the original code. Just replace the cube B with a cylinder

**Comment by zhuyifengzju** [comment]
try to increase `z_offset`. I assume currently the cylinder is initialized to penetrate the table, and creating large force on the object.

**Comment by YunchuZhang** [comment]
I change the z_offset to 0.1, but it still has the weird performance

**Comment by YunchuZhang** [comment]
I also troed CapsuleObject, BallObject
and those works well except the cylinder

**Comment by cremebrule** [comment]
Hi, I have been able to reproduce your issue. Will look into this to see if there's an easy fix.

**Comment by YunchuZhang** [comment]
> Hi, I have been able to reproduce your issue. Will look into this to see if there's an easy fix.

I tried to parse  solimp = [0.998, 0.998, 0.001], solref = [0.001, 1],
but still does not work

**Comment by yukezhu** [comment]
This issue has been resolved in PR #213
