### ISSUE TITLE
table_arena correction and infinte plane problem

### ISSUE THREAD

**Issue by bebbo203** [ARISE-Initiative/robosuite#194]
When using table_arena, the contact geometry of the table is a box. With some meshes it can cause instability on the contacts computations.
When changing it to a plane, the contacts are computed correctly but the plane is interpreted as infinite though the size is not zero.

This is the change made to the table_arena.xml. Note that a little displacement is added to the plane in such a way that it's prefectly placed on top on the taaple

`<body name="table" pos="0 0 0.4">
 <geom pos="0 0 0" size="0.4 0.4 0.4" type="plane" group="0" name="table_collision" friction="1 0.005 0.0001" condim="3" zaxis="0 0 1" rgba="1 0 0 1"/>
<geom pos="0 0 -0.014" size="0.4 0.4 0.4" type="box" conaffinity="0" contype="0" group="1" name="table_visual" material="table_ceramic"/>
 <site pos="0 0 0" name="table_top" size="0.001 0.001 0.001" rgba="0 0 0 0"/> 
`

This is the image of the bug: the table top visual has been removed to show the correctly rendered contact_geometry.
The object are now stable and don't show the instable effects generated by the box. 
The plane is infinte while it's defined as not infinite.

![Image](https://user-images.githubusercontent.com/5352494/109128537-e1d6bb00-774f-11eb-840e-690f1f475ded.png)

**Comment by cremebrule** [comment]
Hi @bebbo203 , thanks for bringing this up. Indeed, you are correct that plane geometry plays nicer with contacts. I actually had tried to do what you're doing for our v1.0 release, but found that (as far as I'm aware) planes unfortunately cannot be anything other than infinite for collision purposes. The "size" settings only impact rendering. See the [XML Reference](http://www.mujoco.org/book/XMLreference.html#geom) for details

**Comment by bebbo203** [comment]
Thank you
