### ISSUE TITLE
About 1.2 new Improvements for grippers

### ISSUE THREAD

**Issue by YunchuZhang** [ARISE-Initiative/robosuite#196]
Hi there,
In the 1.2 releasing, it says:
Tuned parallel jaw grippers (PandaGripper and RethinkGripper) for improved grasp stability and significantly reduced sliding

Could you guys ping me for where it was changed?

Thanks

**Comment by cremebrule** [comment]
The commit corresponding to that change can be found [HERE](https://github.com/ARISE-Initiative/robosuite/commit/348ecffec20f35e768eb150204dbd7641d498231).
