### ISSUE TITLE
Can I use camera obervation with 1 GPU

### ISSUE THREAD

**Issue by huang1997214** [ARISE-Initiative/robosuite#199]
When I make the environment.

env = nl_guide_lift_env(
    robots="Sawyer",  # try with other robots like "Sawyer" and "Jaco"
    has_renderer=False,
    has_offscreen_renderer=True,
    use_camera_obs=True,
    ignore_done=True,
    render_visual_mesh=True,
    control_freq=20,
)

The following error occurs
  File "mujoco_py/mjrendercontext.pyx", line 45, in mujoco_py.cymj.MjRenderContext.__init__
  File "mujoco_py/mjrendercontext.pyx", line 113, in mujoco_py.cymj.MjRenderContext._setup_opengl_context
  File "mujoco_py/opengl_context.pyx", line 130, in mujoco_py.cymj.OffscreenOpenGLContext.__init__
RuntimeError: Failed to initialize OpenGL

This seems to result in 1 GPU. I wondering if there is some way that I can use 1GPU to get the image observation.
I want to use image observation to train a DQN.
Thanks!

**Comment by hermanjakobsen** [comment]
This is a known issue with mujoco-py and rendering. I have posted a similar [issue](https://github.com/ARISE-Initiative/robosuite/issues/114) some time ago :)

**Comment by huang1997214** [comment]
Sorry, I am not familiar with mujoco-py.

**Comment by RayYoh** [comment]
> This is a known issue with mujoco-py and rendering. I have posted a similar [issue](https://github.com/ARISE-Initiative/robosuite/issues/114) some time ago :)

So how to solve this problem?

**Comment by peterdavidfagan** [comment]
@RayYoh it is a bit of a hack but you can use the following from my experience: https://github.com/openai/mujoco-py/issues/268#issuecomment-968205448

Kudo to @HesNobi

**Comment by RayYoh** [comment]
> @RayYoh it is a bit of a hack but you can use the following from my experience: [openai/mujoco-py#268 (comment)](https://github.com/openai/mujoco-py/issues/268#issuecomment-968205448)
> 
> Kudos to @HesNobi for this.

Thanks a lot. Hope it works.
