### ISSUE TITLE
How to fix an object on the table?

### ISSUE THREAD

**Issue by csufangyu** [ARISE-Initiative/robosuite#200]
hi，thanks your works.I want to create my own task,and I want to fix an object on the table,how can I do it?

**Comment by cremebrule** [comment]
Hi @csufangyu , 

You can "fix" an object (i.e.: remove its free joint) by simply setting `joints=None` when you create the object. Please check out our docs on, e.g., [primitive objects HERE](http://robosuite.ai/docs/source/robosuite.models.objects.html?highlight=primitiveobject#robosuite.models.objects.generated_objects.PrimitiveObject) for more information
