### ISSUE TITLE
can you share the code in VICES?

### ISSUE THREAD

**Issue by csufangyu** [ARISE-Initiative/robosuite#202]
hi I read the paper [Variable Impedance Control in End-Effector Space: An Action Space for Reinforcement Learning in Contact-Rich Tasks](https://arxiv.org/abs/1906.08880), but I not find the code in paper,the code seems to only open source the training environment.
thanks very much!

**Comment by yukezhu** [comment]
Please check out this branch: https://github.com/ARISE-Initiative/robosuite/tree/vices_iros19

**Comment by csufangyu** [comment]
yes I'm reading this branch,but in the code, I can not find the train file,and i find the [config file](https://github.com/ARISE-Initiative/robosuite/tree/vices_iros19/robosuite/scripts/config),but not find how to train or use it. can you help me?thanks very much.
