### ISSUE TITLE
pick_place objects' setting

### ISSUE THREAD

**Issue by caishanglei** [ARISE-Initiative/robosuite#206]
How to fix the object in the center of the box on the left in pick_place, and how to rotate it according to the xyz axis

**Comment by cremebrule** [comment]
Hi @caishanglei ,

You can specify these things (and others) using the args in the `UniformRandomSampler`. e.g.: for specifying the sampling x-y position, you would set [THIS LINE](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/pick_place.py#L406). For setting a rotation, you would set [THIS LINE](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/pick_place.py#L408) and the following line that proceeds it. I would also recommend you see our docs on [Placing Objects](http://robosuite.ai/docs/modules/objects.html#placing-objects).

Closing this issue for now, feel free to re-open it or start a new issue if you have further problems.
