### ISSUE TITLE
Bug report: site visibility setting

### ISSUE THREAD

**Issue by guodashun** [ARISE-Initiative/robosuite#210]
I customized a gripper and needed to add a force sensor. The visible site will show me whether I set the correct postion of the sensor. I've viewed the codes and found the visibility of the gripper's site is `off` by default. However, the reflection on the ground shows the gripper's site (as the following pic shows).
![1618148568452](https://user-images.githubusercontent.com/22697937/114306948-25bf2d00-9b10-11eb-997d-305c3510843c.jpg)
At first I didn't know what the cylinder in the reflection was and finally I find the answer in my gripper's json.
```json
<site name="grip_site_cylinder" pos="0 0 0.1399" size="0.005 10" rgba="0 1 0 0.3" type="cylinder" group="1"/>
```
Hopeful for this bug can be fixed.
Thanks!

**Comment by yukezhu** [comment]
This seems to be an incorrect rendering behavior caused by MuJoCo's internal OpenGL renderer. I don't think there is an easy fix on our end. Did you manage to find a solution to this?
