### ISSUE TITLE
Extra space in Kinova3 robot.xml causes it to break.

### ISSUE THREAD

**Issue by divyanshj16** [ARISE-Initiative/robosuite#211]
https://github.com/ARISE-Initiative/robosuite/blob/65d3b9ad28d6e7a006e9eef7c5a0330816483be4/robosuite/models/assets/robots/kinova3/robot.xml#L73

There is a extra space in the values of quat which breaks the `string_to_array` function.

**Comment by yukezhu** [comment]
Addressed in PR #213
