### ISSUE TITLE
request for multiple robots in environment

### ISSUE THREAD

**Issue by ava6969** [ARISE-Initiative/robosuite#212]
I think an additional feature to this awesome library wold be to have multiple robots spawned in an envrionemnt, as it reduces the  memory overhead of running from a mujoco sim. have 1 to many data transfer will help in increasing sample bandwith.

**Comment by yukezhu** [comment]
Good suggestions. We have examples of two-arm tasks that spawn two robots in an environment. This can be easily extended to multiple arms as demonstrated in our [recent work](https://roboturk.stanford.edu/multiarm). This is left to the robosuite users to create on their own.
