### ISSUE TITLE
Add task-irrelevant robots into background of existing environment

### ISSUE THREAD

**Issue by jetnew** [ARISE-Initiative/robosuite#220]
Is it possible to add task-irrelevant robots into the background of existing environments? In particular, I am trying to insert an arbitrary, randomly-moving robot arm into the background of a the [two-arm peg-in-hole environment](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/two_arm_peg_in_hole.py), perhaps beside the two arms. Is there example code available for this? Thanks in advance!

**Comment by yukezhu** [comment]
You can adapt the [TwoArmEnv](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/two_arm_env.py) class to extend the manipulation environments to have three or more arms. This was done in our recent [multi-arm roboturk paper](https://roboturk.stanford.edu/multiarm).
