### ISSUE TITLE
Inefficient learning of OSC Kp values

### ISSUE THREAD

**Issue by hermanjakobsen** [ARISE-Initiative/robosuite#221]
Hey! 

I have been spending some time with the OSC and its different modes. More specifically, I am using the OSC as the low-level controller when training my RL models. 

What I have encountered for the "variable" and "variable_kp" mode is that the learning of Kp values is extremely inefficient. In my case, the Kp values should often have values equal to ~100 for the controller to have a desirable performance. The problem is that the neural networks for the RL algorithms often give outputs around ~1 or ~10 (ref. PPO in stable_baselines3). As a result, the network weights have to change a lot in order to output values ~100. 

I am proposing a solution to this problem by scaling the Kp values, as done with the other inputs (delta). 

I will be happy to make a PR if there are others that also struggles with this problem :)

**Comment by roberto-martinmartin** [comment]
Hi Herman,

the scaling issue makes sense. However, I think any scaling should happen **outside** the controller. Our controllers are generic physical interfaces to define robot motion and contact behavior. We do not assume the input comes always from a NN (with outputs in -1, 1, or similar). The equivalent would be to force users of a joint position controller to give desired joint configurations between -1 and 1 that we would scale to the physical joint values. That can be confusing. Kp has a physical meaning, including physical units (e.g. N/m for forces), in the same way that joint configurations are radians.

What I would recommend is to scale the input to the controller. The same process you make "inside" the OSC impedance controller, but outside. The behavior would be the same for you, but the controller remains agnostic.
