### ISSUE TITLE
Roboturk hdf5 contents

### ISSUE THREAD

**Issue by xtkisscs** [ARISE-Initiative/robosuite#223]
Hey,

I have some problems with processing roboturk datasets for my current work. What does each column in the "status (dataset)-flattened MuJoCo states, ordered by time" in the roboturk simulation data set mean, because I want to retrieve some information I need, but unfortunately I can't find any explanation about what do these datasets represent.

Thanks for your help in advance :)

**Comment by amandlek** [comment]
You can take a look at [this example](https://github.com/ARISE-Initiative/robosuite/blob/v0.3/robosuite/scripts/playback_demonstrations_from_hdf5.py#L100) (from v0.3, which is the version of robosuite that the RoboTurk datasets were collected with) to see how the states are supposed to be used to reset the simulation state to the recorded configuration. After resetting the environment to a state along the trajectory, you can then retrieve any observations of interest (e.g. using [get_observation](https://github.com/ARISE-Initiative/robosuite/blob/v0.3/robosuite/environments/sawyer_lift.py#L254)), and collect them into an observation to be used for learning at that timestep. Hope that helps!
