### ISSUE TITLE
Lifting randomized values affects reward

### ISSUE THREAD

**Issue by ava6969** [ARISE-Initiative/robosuite#224]
HI I realized when i trained the agent for lift on the cube and tested on random objects, it transferred the skill really nicely, I instead wanted to train on different shapes with different geometry but its affecting the reward signals, is there any suggestion on how this can be done to make lift reward agnostic to the geometry of the object. Also the cylinder seems to collide with the table at launch

   objects = [

            BoxObject(
                name="obj",
                size_min=[0.015, 0.015, 0.015],  # [0.015, 0.015, 0.015],
                size_max=[0.022, 0.022, 0.022],  # [0.018, 0.018, 0.018])
                rgba=[1, 0, 0, 1],
                material=redwood,
            ),

            # CapsuleObject(
            #     name='obj',
            #     size_min=[0.015, 0.015],  # radius height,
            #     size_max=[0.022, 0.022],  #
            #     rgba=[1, 0, 0, 1]
            # ),
            #
            # BallObject(
            #     name='obj',
            #     size_min=[0.015],  # radius height,
            #     size_max=[0.022],  #
            #     rgba=[1, 0, 0, 1]
            # ),

            # MilkObject("obj"),
            # BreadObject("obj"),
            # CerealObject("obj"),
            # CanObject("obj"),
            # LemonObject("obj"),
            # BottleObject("obj")

        ]

        self.object = random.choice(objects)

**Comment by yukezhu** [comment]
To extend the reward function to different shapes with different geometries, you'd need to update the reward function definition here: https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/lift.py#L193
