### ISSUE TITLE
Visual and collision model not syncing

### ISSUE THREAD

**Issue by SuryaPratapSingh37** [ARISE-Initiative/robosuite#225]
I am trying to add a custom stl file to robosuite gym environment but I am getting the visual and collision model of the stl seen separately in the environment, as can be seen in the attached image. In the image the black colored model is the visual model being apparently held (and floating as well in space) by the gripper of UR5e whereas the white colored one is the collision model placed on the table.  Can someone please help me in syncing these two models?
![vis1](https://user-images.githubusercontent.com/70885700/117065616-5a0bbf00-ad45-11eb-9b68-bdb39373db3e.png)

**Comment by yukezhu** [comment]
Hi @SuryaPratapSingh37 This is a general MuJoCo issue on how visual and collision geoms are defined. I suggest you post your question on the general MuJoCo Forum for help.
