### ISSUE TITLE
Uncoupling in OSC

### ISSUE THREAD

**Issue by Wenxuan-Zhou** [ARISE-Initiative/robosuite#226]
I'm wondering what's the benefit of [uncoupling the lambda matrix in OSC](https://github.com/ARISE-Initiative/robosuite/blob/65d3b9ad28d6e7a006e9eef7c5a0330816483be4/robosuite/controllers/osc.py#L329). Is there a paper that I can refer to for this part? Thanks in advance!

**Comment by roberto-martinmartin** [comment]
There are no papers about it, sorry. It is an empirical measure to separate the dynamics compensation in position and orientation control. This is useful when there are unmodelled dynamic effects, e.g. deviations between the dynamics model and the true dynamics model (not in sim) or unmodelled contacts. It improves the behavior and stability of the controller
