### ISSUE TITLE
Any idea of how to buy a MuJoCo Institutional License ?

### ISSUE THREAD

**Issue by jrabary** [ARISE-Initiative/robosuite#229]
Thank you for releasing robosuite which is a valuable tool for researchers in robotic field and reinforcement learning. 
We really would like to use it but we are facing a big obstacle: MuJoCo! 
We trying to buy an Institutional license from Roboti but it turns out that they don't respond to any of our emails. We are wondering whether Roboti still exists and still sells MuJoCo.
As you choose to build robosuite on top of MuJoCo maybe you know how to reach Roboti people. It will be helpful if you can help us to contact them so we can buy a license in order to use robosuite in our every day research.

**Comment by yukezhu** [comment]
Sorry that we can't offer help with MuJoCo licensing. Please seek help on the MuJoCo forum instead http://www.mujoco.org/forum/index.php
