### ISSUE TITLE
pip install robosuite can't find module `robosuite.demos`

### ISSUE THREAD

**Issue by siddk** [ARISE-Initiative/robosuite#233]
When running `pip install robosuite` (via PyPI), I get the error `ModuleNotFoundError: No module named 'robosuite.demos'` when attempting to run `python -m robosuite.demos.demo_random_action` from the installation page. 

On further inspection, seems like `demos` just isn't a package in the library (see screenshot below). I dug around in the code, and it just seems like there's a missing `__init__.py` in the `demos/` sub-directory (and probably a few higher level things in the `setup.py`) to include it in the PyPI distribution.

![Screen Shot 2021-06-08 at 9 23 14 PM](https://user-images.githubusercontent.com/2498509/121360025-e67f4380-c8e8-11eb-8321-89a32ab0ed86.png)

**Comment by yukezhu** [comment]
Thanks! This has been fixed in the latest pip package: https://pypi.org/project/robosuite/1.2.2/
