### ISSUE TITLE
Custom Controller

### ISSUE THREAD

**Issue by garlicbutter** [ARISE-Initiative/robosuite#234]
Hi, 
Our team is working with the robosuite to simulate the robot for our lab.
However, the controller we need is not in the options that ROBOSUITE provides.
Is there anyway to write our own custom controller?

We are going to write the Impedance controller
https://en.wikipedia.org/wiki/Impedance_control

**Comment by cremebrule** [comment]
Hi @garlicbutter ,

Yes! You can implement your own controller class via the following steps:

1. Implementing your own controller class as a subclass of `Controller`.
2. Adding your controller to `controller_factory` in `robosuite/controllers/controller_factory.py`
3. Registering your controller in `robosuite/controllers/__init__.py`.

You can see some of our controllers for specifics on how we generally implement the controller loop. In general, you need to implement `set_goal`, `run_controller`, `reset_goal`, and `name` at the very minimum in your controller.

**Comment by garlicbutter** [comment]
Thank you!
