### ISSUE TITLE
How to use FrontView to view an environment with image information in the observation space

### ISSUE THREAD

**Issue by caishanglei** [ARISE-Initiative/robosuite#244]
Can you use frontview to observe the trained model with the robot using the hand-eye camera? There is a conflict between render_camera and camera

**Comment by yukezhu** [comment]
Yes, you can use both cameras by providing their names to the `camera_names` argument of the environment constructor. Once getting both camera observations, write the frontview camera to a video file and use the hand-eye camera as input to your model.
