### ISSUE TITLE
How to move objects during simulation?

### ISSUE THREAD

**Issue by SuryaPratapSingh37** [ARISE-Initiative/robosuite#245]
Is there anyway by which I can move objects(or change their position) such as 'can', 'bread' and even 'table' during a simulation at every time step?

**Comment by amandlek** [comment]
Yes, I believe setting the qpos values should be sufficient. Take a look at [this example](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/base.py#L460) - we use this in the single-object versions of the PickPlace task to move the other objects far away.
