### ISSUE TITLE
How to save the end-effector position and the gripper state of the robot arm when saving the human demonstration

### ISSUE THREAD

**Issue by karthikarvind1295** [ARISE-Initiative/robosuite#246]
I would like to save the end-effector position of the robotic arm and the gripper state of the robot. Is it possible to save it in the Data_collection_wrapper ?

**Comment by amandlek** [comment]
We save the raw mujoco states to make it easy to back out different observations of interest in a postprocessing step. We've also recently released a codebase and standardized set of demonstration datasets - you can read more about extracting observations from the datasets [here](https://arise-initiative.github.io/robomimic-web/docs/introduction/datasets.html#extracting-observations-from-mujoco-states) -- the codebase is also compatible with demonstrations you collect through robosuite.
