### ISSUE TITLE
Jaco Sim and Real Mismatches

### ISSUE THREAD

**Issue by melfm** [ARISE-Initiative/robosuite#263]
I'm working on the Jaco arm, performing some testing on the simulated Jaco to the real Jaco arm controller transfer. I'm finding some inconsistencies:

1) The robot's initial position is incorrectly rotated (on the real arm the power cable is typically on the back of the arm when the arm is set to the home position). To fix this, inside the Jaco xml descriptor I rotated the base to match the real arm where the power cable is on the back. I noticed inside the [user manual](https://www.kinovarobotics.com/sites/default/files/ULWS-RA-JAC-UG-INT-EN%20201804-1.0%20%28KINOVA%E2%84%A2%20Ultra%20lightweight%20robotic%20arm%20user%20guide%29_0.pdf) the power cable appears on the side, but on the real arm, set to the home pose its actually on the back.

![PXL_20211027_155739482_mini](https://user-images.githubusercontent.com/1942293/139104993-b5050d99-bfc3-4be2-af3d-4c1a68c5eeec.jpg)
![PXL_20211027_155759242_mini](https://user-images.githubusercontent.com/1942293/139105125-7345dad7-61d1-4691-a7a1-d11c433a791f.jpg)

```
Inside : robosuite/models/assets/robots/jaco/robot.xml
<body name="j2s7s300_link_0" pos="0 0 0" quat="0.707107 0 0 0.707107">
```

The initial position of the real Jaco is also the following:
```
Inside: robosuite/models/robots/manipulators/jaco_robot.py
    def init_qpos(self):
        # Jaco Real home pose
        return np.array([4.942, 2.842, 0.0011, 0.758, 4.6368, 4.492, 5.0244])
```

But I understand this is a design choice and perhaps for consistency of the initial pose with other arms as well. Either the real arm needs to be sent to the sim home pose or the other way round.

2) Sim vs Real controller inconsistencies
There are some issues with the assumed reference coordinates frames between the real and the sim which I can discuss in more detail - this only affects the end-effector control. I can give you the utility functions you'd need to transform these into the real arm coordinate frame.

~~But first I'd like to discuss just the joint pose matching on the real and sim arms. I was unable to get a perfectly matching poses.~~
UPDATE: I realized this is an initialization issue - with OSC, initially the poses mismatch but as the arm moves, they get corrected. This problem doesn't occur with joint position controller however.

**Comment by cremebrule** [comment]
Hi @melfm ,

Apologies for the delay in responding to this issue.

> But I understand this is a design choice and perhaps for consistency of the initial pose with other arms as well. Either the real arm needs to be sent to the sim home pose or the other way round.

Yes, that's exactly how we determined the initial qpos -- it was mainly for consistency, not actual real-robot values. It would be very useful, however, to have alternate init_qpos's corresponding to the "real" init qpos, as you described! Thanks for sharing this info.

> UPDATE: I realized this is an initialization issue - with OSC, initially the poses mismatch but as the arm moves, they get corrected. This problem doesn't occur with joint position controller however.

Can you be more specific with regards to the initial "pose mismatch" that gets corrected as the arm moves?

**Comment by cremebrule** [comment]
Hi @melfm , 

Since there hasn't been a response for awhile, I'm going to close this issue for now. Feel free to reopen if you have additional questions / problems!

**Comment by melfm** [comment]
Hi @cremebrule,

Apologies for the delay. Yes please feel free to close this issue now, the code snippet above should fix the mismatch in the orientations of the physical robot. There will be more conversion needed for sim2real transfer of end-effector controllers, although I'm not sure how you want to include such utility functions.

As for the OSC mismatch, I noticed when comparing the arms (sim and real) set to the same initial positions, the initial poses don't match but as you apply control inputs, the joint positions get corrected. If I remember correctly, it looked something like this :

![OSC_im_joint_position_vs_real](https://user-images.githubusercontent.com/1942293/155400734-8346f380-d0bf-4842-b51c-644342b17397.png)
