### ISSUE TITLE
How do I get joint positions in the environment

### ISSUE THREAD

**Issue by caishanglei** [ARISE-Initiative/robosuite#268]
How can the posture of each joint be obtained in the state space, where there is only the grip posture, and the joint angle？

**Comment by cremebrule** [comment]
Hi @caishanglei ,

Apologies for the delay in response. Are you referring to the joint positions for the robot? If so, you can directly call them, e.g., `env.robots[0]._joint_positions` for the 0th robot in the environment.

Closing this for now. Feel free to reopen if there are further issues!
