### ISSUE TITLE
Query about eef_pos and eff_quant in the Observation

### ISSUE THREAD

**Issue by BillHan-Fantast** [ARISE-Initiative/robosuite#271]
Hi, which reference frame are the eef_pos and eef_quant  in the observation space computed? If it is computed relative to the same world frame, can I assume that these two observations are shared among different robots on the same task (e.g., the same eef_pos means visual eef position)?

**Comment by cremebrule** [comment]
Hi @BillHan-Fantast ,

Apologies for the delay in response. Great question! They are computed in the world frame, and should be consistent between different robots.
