### ISSUE TITLE
lowercasing of DAE and STL file extension in robot URDF necessary for IK control

### ISSUE THREAD

**Issue by hueds** [ARISE-Initiative/robosuite#272]
The assets have lowercased `.DAE`, `.STL` files extensions, but the URDF has capitalized `.DAE` and `.STL` file extensions. This causes a pybullet error on loading the URDF for the IK_POSE controller. To fix, the URDF needs to be updated.   

This was referenced in a previous issue:

---
It means [this file](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/assets/bullet_data/sawyer_description/urdf/sawyer_arm.urdf) lines.

If you look at this lines(32, 52, 80, 107, 134, 161, 189, 216), you can see that it is capitalized.

Thanks for your reply.

_Originally posted by @jdj2261 in https://github.com/ARISE-Initiative/robosuite/issues/238#issuecomment-871080113_

**Comment by yukezhu** [comment]
@awesome-aj0123 can you make a PR to address this?

**Comment by yukezhu** [comment]
Thank you for reporting @hueds ! This should be fixed now.
