### ISSUE TITLE
Unable to integrate igibson renderer

### ISSUE THREAD

**Issue by qq456cvb** [ARISE-Initiative/robosuite#284]
I follow the instructions on https://stanfordvl.github.io/iGibson/installation.html to install iGibson 2. However, on https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/renderers/igibson/igibson_renderer.py#L17, 'Instance' and 'Robot' class seems only exists in iGibson 1. Then, I tried the following:

1. Install iGibson 1 instead of iGibson 2. However, this brought me a lot of errors when invoking iGibson API (e.g., MeshRendererSettings does not accept 'is_robosuite' argument)
2. Modify the robosuite code by replacing 'Instance' with 'InstanceGroup' and 'Robot' with 'BaseRobot'. However, this also brought me an error "AttributeError: 'MeshRenderer' object has no attribute 'add_robot'" at https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/renderers/igibson/parser.py#L139.

Which version is compatible with robosuite?

**Comment by yukezhu** [comment]
The iG renderer's support has recently been updated. It should work with the latest version of robosuite.
