### ISSUE TITLE
MujocoXMLObject not experiencing gravity, and remains suspended in environment space

### ISSUE THREAD

**Issue by SuryaPratapSingh37** [ARISE-Initiative/robosuite#289]
Hi,

I am trying to load an object into the robosuite environment using the following code:

![code](https://user-images.githubusercontent.com/70885700/151698228-6d0610c9-a793-4a04-9c48-613b024af51d.jpg)

And, I do see the object in the environment but it doesn’t seem to be a free body, as it is suspended in space and not experiencing any gravity, even though both the collision and visual mesh are in sync, as can be seen in the attached picture.

![robosuite_environment](https://user-images.githubusercontent.com/70885700/151698248-8f56fb9f-fc82-4e33-99cf-fd731a2719a7.jpg)

Secondly, if I provide this MujocoXMLObject position coordinates as if it is sitting on top of a moving BoxObject, which acts as a conveyor, then the MujocoXMLObject doesn’t move with the BoxObject and remains stick to its original position in space. Furthermore, if a second BoxObject is placed on top of the moving conveyor, the second BoxObject does move with the conveyor. In fact, the second BoxObject, if it collides with the MujocoXMLObject, is also not able to push the MujocoXMLObject. I find it pretty weird why the MujocoXMLObject doesn’t show the same behaviour like a BoxObject. So can someone please help me resolve these issues? I'm also attaching the MujocoXMLObject's collision and visual xml files.

![canobject](https://user-images.githubusercontent.com/70885700/151698264-488f97e2-2d37-42ed-ba4b-1d1732290de2.jpg)
![canvisualobject](https://user-images.githubusercontent.com/70885700/151698268-9d17d892-19cb-4bd1-ba08-331ff71b0ba1.jpg)

Thanks in advance

**Comment by cremebrule** [comment]
Hi @SuryaPratapSingh37 ,

Thanks for providing details on your problem. Can you provide a stand-alone script to reproduce this issue? I think the code snippet you provided was copy + pasted from somewhere else, since there's some variables (e.g. `world`) that aren't instantiated anywhere in the snippet. Thanks!
