### ISSUE TITLE
TwoArmLift can be solved with single arm

### ISSUE THREAD

**Issue by ElieAljalbout** [ARISE-Initiative/robosuite#310]
The current version of the TwoArmLift environment can be trained to reach (almost) max reward while using a single arm only. At least I know that to be true when using reward_shaping, but it should also be possible with the dense reward.  This can probably be solved by increasing the object weight or changing the reward definition. However, It would be nice to have a standardized solution for everyone.

**Comment by yukezhu** [comment]
Thanks for the notice. Given that this task has been used for standardized benchmarking, I would consider it to be a feature, not a bug. I did remember trying to increase the object weights but encountering physical instability or the object slipping out of the grippers. Please feel free to make modifications to the task for your own research needs.
