### ISSUE TITLE
Consider Using dm_control for mujoco python bindings

### ISSUE THREAD

**Issue by lapp0** [ARISE-Initiative/robosuite#313]
Currently robosuite requires a fork of `mujoco-py` called `free-mujoco-py`. This is a fork of https://github.com/openai/mujoco-py/ which is in "maintenance mode", has 23 open pull requests the last of which was merged in November 2021.

The [mujoco repo](https://github.com/deepmind/mujoco) and project is run by DeepMind, as is [dm_control](https://github.com/deepmind/dm_control/tree/master/dm_control/mujoco). The dm_control python bindings for mujoco are actively maintained.

Disclaimer: I'm asking not only for the above-stated reason. I'm also asking because myself and many others are having trouble with [mujoco-py based mujoco rendering resulting in a segfault](https://github.com/openai/mujoco-py/issues/57#issuecomment-1046131727).

**Comment by yukezhu** [comment]
dm_control's interfaces have been migrated to the newly released Python binding of [mujoco](https://mujoco.readthedocs.io/en/latest/python.html). We have been having internal discussions on migrating to this new binding, which as you suggested has longer-term support. The migration would take a substantial amount of effort as the new binding offers a lower level of abstraction than mujoco-py. So I anticipate that it will eventually happen but might take several months of effort.

**Comment by jgsimard** [comment]
Hi, any news on this?

**Comment by yukezhu** [comment]
Still working on this. Things have been slower due to the summer hiatus. Should expect this to be out in 1 month.

**Comment by jgsimard** [comment]
oki thanks!

**Comment by beneisner** [comment]
+1 looking forward to seeing this! the new mujoco bindings might also allow for better, multithread/process support...
