### ISSUE TITLE
How to cancel random  of object location

### ISSUE THREAD

**Issue by xuweiqiang486** [ARISE-Initiative/robosuite#314]
I hope to fix the position of the manipulator and  the object during make env and env.reset，rather than random sampling in pick_place env.
For the position of the manipulator, I set 'initialization_noise=None' during make env, but how to fix the position of the object.
I try to set self.deterministic_reset to true in line 125 of base.py, but then object disappears.

![2022-04-04 23-59-06 的屏幕截图](https://user-images.githubusercontent.com/71928837/161584487-17ae7344-0434-4a02-8c28-020e4628a95e.png)
![2022-04-04 23-57-57 的屏幕截图](https://user-images.githubusercontent.com/71928837/161584502-7d45656d-543c-46c6-a1f5-efa4ddf8f8b7.png)

**Comment by amandlek** [comment]
You can modify the sampling logic [here](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/pick_place.py#L420) (or by making a new environment by subclassing this environment and overriding this function). Then, you can visualize the initial distribution of object placements by using this script [here](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/scripts/make_reset_video.py).
