### ISSUE TITLE
Velocity Cartesian space controller

### ISSUE THREAD

**Issue by TexnoMann** [ARISE-Initiative/robosuite#317]
Hi I'm developing a custom environment for two-hand control and I want to use speed control in Cartesian space. Do you have plans for this type of controller?

**Comment by cremebrule** [comment]
Hi @TexnoMann ,

We don't explicitly support speed control in Cartesian space, but there's a couple workarounds you could try:

1. Using delta positions as a proxy for velocity. Based on your control frequency, you can estimate the desired velocity via `delta_pos / control_freq`.

2. OSC actually natively supports EEF velocity setpoints; we just don't explicitly expose it (in fact, we assume the desired velocity is 0). You can easily expose it by modifying [THIS LINE](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/controllers/osc.py#L316), adding a `desired_vel` term similar to the `desired_pos` line immediately preceding it.

Closing this issue for now, feel free to reopen / start a new issue if you continue to run into problems.
