### ISSUE TITLE
Depth map couldn't detect obejct

### ISSUE THREAD

**Issue by SeungyounShin** [ARISE-Initiative/robosuite#319]
![image](https://user-images.githubusercontent.com/20262536/164522980-36807ce2-85de-4562-955e-ddf9ca01e6e1.png)

the block on the center are not recognize on depth map 
how can I solve this issue?

**Comment by zhuyifengzju** [comment]
Hi, do you mind telling us which version you are using and which robot arm you are using?

**Comment by SeungyounShin** [comment]
@zhuyifengzju I am using `robosuite==1.3.1` and `UR5e`
