### ISSUE TITLE
load objects in urdf format

### ISSUE THREAD

**Issue by shivanimall** [ARISE-Initiative/robosuite#320]
Do you support converting URDF to MJCF format? For example- objects in BEHAVIOUR and Partnet are in URDF format, in case you have pointers / examples for loading these objects?

I saw this https://github.com/eric-heiden/URDF2MJCF

Thanks for your help!

**Comment by cremebrule** [comment]
Hi @shivanimall ,

You can also try using this [rudimentary guide](https://docs.google.com/document/d/1bSUKkpjmbKqWyV5Oc7_4VL4FGKAQZx8aWm_nvlmTVmE/edit?usp=sharing) I put together awhile ago. This guide specifically is meant for importing custom robot models, but the general process is similar for arbitrary objects.

Closing this issue for now, feel free to reopen or start a new issue if you continue to run into issues.
