### ISSUE TITLE
"No "site" with name <>" error when accessing "_eef_xmat" properties

### ISSUE THREAD

**Issue by misoshiruseijin** [ARISE-Initiative/robosuite#321]
Accessing `_eef_xmat` property in `single_arm_env`  or the `_eef0_xmat` and `_eef1_xmat` properties in `two_arm_env`, causes an error "Value Error: No "site" with name robot0_ee exists." The error is resolved with these changes to `_eef_xmat`, `_eef0_xmat`, and `_eef1_xmat`:

- replacing "ee" with "grip_site" and "right_ee" with "right_grip_site"
- replacing `pf = self.robots[0].robot_model.naming_prefix` with `pf = self.robots[0].gripper.naming_prefix`

**Comment by cremebrule** [comment]
Hi @misoshiruseijin ,

Thanks for finding this bug! Can you submit a PR with the appropriate fixes? Thanks!

**Comment by cremebrule** [comment]
Thanks for fixing this! Closing now.
