### ISSUE TITLE
Weird igibson rendering when another another model is instantiated

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [ARISE-Initiative/robosuite#327]
Hi!

I'm getting some weird rendering behavior with the igibson renderer. The first set of images comes from first instantiating a neural network and then rendering. The second set of images comes from directly rendering the igibson camera:

![pure_test0](https://user-images.githubusercontent.com/33344633/167969681-5f5d178e-eb35-42d4-85c7-66dd23d659f2.png)
![pure_test1](https://user-images.githubusercontent.com/33344633/167969683-0d411a40-624a-4b67-81c6-6bf127cf0314.png)
![pure_test2](https://user-images.githubusercontent.com/33344633/167969691-0180362e-aa2a-4940-8d50-a94c17ded0fb.png)

![pure_test3](https://user-images.githubusercontent.com/33344633/167969699-f7897d2f-5bc5-4aff-b2f9-d30107091d1d.png)
![pure_test4](https://user-images.githubusercontent.com/33344633/167969703-9beb49b2-06df-4a3b-8f2c-773b179ed25e.png)
![pure_test5](https://user-images.githubusercontent.com/33344633/167969710-2ced8c1f-5ec7-4951-98d4-b1113e399331.png)

Without instantiating network:
![model_uninstantiated0](https://user-images.githubusercontent.com/33344633/167969761-52bd0e83-375f-43e2-bb0a-baeb65e7c60d.png)
![model_uninstantiated1](https://user-images.githubusercontent.com/33344633/167969765-888932e2-3aa4-41ba-a56a-316e8ef283b4.png)

![model_uninstantiated2](https://user-images.githubusercontent.com/33344633/167969771-ba05961c-3184-4518-aa31-c04b8e5f2db1.png)
![model_uninstantiated3](https://user-images.githubusercontent.com/33344633/167969774-cd3ca725-7afc-43f1-9d4a-ff2162b31cca.png)
![model_uninstantiated4](https://user-images.githubusercontent.com/33344633/167969779-123cb4e6-e72b-4919-ab76-f2d88a94217a.png)

Would you know what the issue is?

**Comment by yukezhu** [comment]
Closing this issue as iG renderer is no longer supported in v1.4
