### ISSUE TITLE
Converting OSC_POSE actions to IK

### ISSUE THREAD

**Issue by yuchen93** [ARISE-Initiative/robosuite#331]
Is there a function that allows conversion of actions between different controllers? 
More specifically I am looking for something that converts OSC_POSE actions to IK actions... Thanks!

**Comment by meinczingerm** [comment]
I am looking for the same functionality. Did you find it somewhere? Or did you find a simple solution for calculating the conversion? IMO this functionality could be useful in some cases, especially if you are trying to use demonstrations that used another controller type than your agent.
