### ISSUE TITLE
Implement Custom Controller

### ISSUE THREAD

**Issue by shivanimall** [ARISE-Initiative/robosuite#332]
Has there been any work that tried integrating custom PID controller in robosuite? I saw #50 and reference to joint_vel.py that supports tuning PID values, is this possible for any of the other controllers besides joint_vel? also, in case there are possible considerations before doing so, would be helpful to know.

Thanks for your help!

**Comment by yukezhu** [comment]
Yes, it's certainly possible to implement custom controllers. I suggest you take a look at the files in the `controllers` folder, where we implemented a number of controllers.
