### ISSUE TITLE
haptic feedback

### ISSUE THREAD

**Issue by shivanimall** [ARISE-Initiative/robosuite#333]
Simulators like SAI offer high fidelity force feedback, is there any work / experimental results in robosuite / mujoco that considers accuracy / fidelity for haptic feedback? for eg: this work uses SAI https://github.com/stanford-iprl-lab/multimodal_representation/issues/25

Thank you for your help!

**Comment by kevin-thankyou-lin** [comment]
Unfortunately not yet, but we're open to contributions!
