### ISSUE TITLE
Creating custom objects as visual site

### ISSUE THREAD

**Issue by melfm** [ARISE-Initiative/robosuite#334]
What is the best way to create objects in the scene as non-interacting objects? This could be for instance reacher target or adding object distractors in the scene that are non-relevant. The current `MujocoObject` interfaces assume objects for manipulation.

**Comment by yukezhu** [comment]
You can check [our implementation](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/environments/manipulation/pick_place.py) of the [Pick-and-Place](http://robosuite.ai/docs/modules/environments.html#pick-and-place) task, which includes four non-interacting objects to indicate target locations.
