### ISSUE TITLE
using pybullet server within robosuite

### ISSUE THREAD

**Issue by shivanimall** [ARISE-Initiative/robosuite#336]
Hello, I am hoping to use a library X that has a well-established integration with pybullet (over mujoco). It seems here- you create a pybullet server and call its functions. https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/controllers/ik.py#L37

I am curious if it may be possible to do something similar i.e. within robosuite, create a pybullet server to integrate with library X? And, in case there are any considerations, please let me know.

Thanks for your help, please let me know if my question is unclear.

**Comment by yukezhu** [comment]
We no longer support pybullet issues here. If you are interested in using libraries customized for pybullet with robosuite, you might want to take a look at [perls2](https://github.com/StanfordVL/perls2), which provides standardized interfaces across different simulation platforms. Alternatively, it could be easier if you write your own integration code for robosuite.
