### ISSUE TITLE
ERROR: GLEW initalization error: Missing GL version

### ISSUE THREAD

**Issue by JuliBaCSE** [ARISE-Initiative/robosuite#340]
Hey,
i am trying to run the test for camera transformation on ubuntu 20.04 but it always raise the Glew init error. 
My actual goal is to use visual observation but it seems not to work.

**Comment by jdekarske** [comment]
On the command line, try `export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libGLEW.so`

https://github.com/openai/mujoco-py/issues/172#issuecomment-680701806

**Comment by yukezhu** [comment]
Closing this issue as this should be directed to mujoco-py
