### ISSUE TITLE
Issues with reset() function in MujocoEnv class

### ISSUE THREAD

**Issue by HeegerGao** [ARISE-Initiative/robosuite#342]
Hi, I think there is a problem with the reset() function in MujcoEnv class. If I want to **dynamically generate different objects with different names in the same environment at every episode**, I will get an error when I run `env.reset()`:

```
AssertionError: No valid observable with name mushrooms_pos found. Options are: {'alphabetsoup_to_robot0_eef_pos', 'robot0_eef_pos', 'robot0_joint_vel', 'world_pose_in_gripper', 'robot0_joint_pos', 'robot0_joint_pos_cos', 'alphabetsoup_quat', 'robot0_joint_pos_sin', 'alphabetsoup_pos', 'robot0_gripper_qvel', 'alphabetsoup_to_robot0_eef_quat', 'robot0_gripper_qpos', 'robot0_eef_quat'}
```

I found this is because in the reset() function, it didn't reset the `self._observables` attribute, which may cause the environment still keep the previous `self._observables` attribute. Thus I think we should add following codes after line 265 in the `base.by` file to reset the `self._observables` attribute:
```
# Load observables
if hasattr(self.viewer, "_setup_observables"):
    self._observables = self.viewer._setup_observables()
else:
    self._observables = self._setup_observables()
```

I have tested them and I found it goes well now.

**Comment by yukezhu** [comment]
Thanks for letting us know, @HeegerGao We are in the process of refactoring our observables logic with the new mujoco binding. We will address this problem in our new version.
