### ISSUE TITLE
Issue about converting .urdf to .xml and loading new XML gripper 

### ISSUE THREAD

**Issue by Willy0921** [ARISE-Initiative/robosuite#344]
Hello,

I have tried using your [rudimentary guide](https://docs.google.com/document/d/19aCyQExqCUj_wixnvHOyotfRijxGD9HO4PjxUXbSHTw/edit) which gives the complete tutorial about how to convert .urdf into .xml and import gripper models Into Robosuite.

But I still meet some problems below:
1. After adding following code into .urdf and running  
`./compile PATH_TO_URDF.urdf PATH_TO_OUTPUT_DIR/{YOUR_GRIPPER_NAME}_gripper.xml`,
it will generate a new .xml file, but the contents is empty, and nothing is converted.
```
<mujoco>
    <compiler 
    meshdir="PATH_TO_MESHES_DIRECTORY" 
    balanceinertia="true" 
    discardvisual="false" />
</mujoco>
```

2. I tried to load my own gripper model with .xml format into Robosuite, but it looks like something went wrong when .xml file has `<default class="myclass">` self-defined tag.
It always comes out the error message such as `KeyError: 'myclass'` when I want to import my own gripper into environment.

Thanks.

**Comment by Willy0921** [comment]
Thanks for your reply!

For question 2, I think I have set my own gripper int the name mapping in `__init__.py` correctly.
However, I think the problem might be somewhere else. Maybe something wrong in `mygripper.xml` causes error in `base.py.`

Here is part of the my error message:
  ```
File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 495, in __init__
    super().__init__(fname)
  File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 47, in __init__
    self._replace_defaults_inline(default_dic=default_classes)
  File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 253, in _replace_defaults_inline
    self._replace_defaults_inline(default_dic=default_dic, root=child)
  File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 253, in _replace_defaults_inline
    self._replace_defaults_inline(default_dic=default_dic, root=child)
  File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 253, in _replace_defaults_inline
    self._replace_defaults_inline(default_dic=default_dic, root=child)
  File "/home/wei-chieh/robosuite/robosuite/models/base.py", line 246, in _replace_defaults_inline
    tag_attrs = default_dic[cls_name].get(root.tag, None)
KeyError: 'D_Touch'
```
And my description of default tag in `mygripper.xml`:
```
<default>
        <default class="adroit">
            <joint limited="true" margin="0.01" armature="0.001" damping="0.05" frictionloss="0.001"/>
            <geom friction="1 0.005 0.001" margin="0.0005"/>
            <site rgba="0.4 0.9 0.4 1"/>
            <tendon limited="true"/>
            <general ctrllimited="true" ctrlrange="-1 1"/>
            <default class="D_Touch">
                <site group="4" type="box" rgba="0.8 0.8 0.8 0.25"/>
            </default>
            <default class="DC_Hand">
                <geom conaffinity="0" group="4" material="MatColl"/>
            </default>
            <default class="D_Vizual">
                <geom type="mesh" contype="0" conaffinity="0" group="1" material="MatViz"/>
            </default>
            <default class="wrist_visual">
                <geom type="mesh" contype="0" conaffinity="0" group="1" material="metal"/>
            </default>
        </default>
</default>
```

Sorry for bothering you.

**Comment by zhuyifengzju** [comment]
Hi,
Could you remove `default class` name tags and directly the name in each `geom` definition? If it still doesn't work, could you post `__init__` function so that we can see how you actually initialize the gripper?
