### ISSUE TITLE
Initialise joint positions of a robot

### ISSUE THREAD

**Issue by YC-Liang** [ARISE-Initiative/robosuite#377]
Hi,

I have realised that the ManipulationEnv class, which is inheirted by other single arm environments, does not take initial_qpos as arguments to provide custom initial joint positions for the robot. 

What's the best method to perform robot joint angle initialisation on the custom environment inherited from the SingleArmEnv (and hence ManipulationEnv)?

Thanks

**Comment by zhuyifengzju** [comment]
Hi,
    There are two solutions to this use case. One is that you directly set the desired joint positions in the mjdata. The other option is that you can create your custom robot class that is similar to original one (for example, something like this https://github.com/ARISE-Initiative/robosuite/blob/60b358673cc5aaccbf1dc950dbfe365e0915c69a/robosuite/models/robots/manipulators/panda_robot.py#L7), where the joint positions can be randomly initialized based on your use case (replace https://github.com/ARISE-Initiative/robosuite/blob/60b358673cc5aaccbf1dc950dbfe365e0915c69a/robosuite/models/robots/manipulators/panda_robot.py#L34). We would love to help if you want more concrete
