### ISSUE TITLE
I want to load a flexible cable.

### ISSUE THREAD

**Issue by makitayugo** [ARISE-Initiative/robosuite#380]
I am using ```[7]PickPlaceBread```,```[3] Panda```,```[2] JOINT_POSITION ``` in ```demo_control.py```.
 Then I change ```class BreadObject(MujocoXMLObject)``` in ```xml_objects.py``` to the XML file containing the cable and try to implement the flexible cable for a test.
However, I get the error ```TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType' ```. 
Does this demo not support functions such as ```composite```and its internal parameters?

<details>
  <summary>minimal XML</summary>

```XML
<mujoco model="cable">
  <asset>
    <mesh file="meshes/bread.stl" name="bread_mesh" scale="0.8 0.8 0.8"/>
    <texture file="../textures/bread.png" type="2d" name="tex-bread" />
    <material name="bread" reflectance="0.7" texrepeat="15 15" texture="tex-bread" texuniform="true"/>
  </asset>
  <worldbody>
    <body>
      <body name="object">
        <composite type="cable" curve="s" count="41 1 1" size="0.1" pos="-0.05 0.2 .02" solimp="0.998 0.998 0.001" solref="0.001 1" density="50" friction="0.95 0.3 0.1"  material="bread" group="0" condim="4">
          <plugin plugin="mujoco.elasticity.cable">
            <config key="twist" value="1e2"/>
            <config key="bend" value="1e3"/>
          </plugin>
          <joint kind="main" damping=".01"/>
          <geom type="capsule" size=".005" rgba=".8 .2 .1 1" friction="1" condim="1"/>
        </composite>
      </body>
      <site rgba="0 0 0 0" size="0.005" pos="0 0 -0.045" name="bottom_site"/>
      <site rgba="0 0 0 0" size="0.005" pos="0 0 0.03" name="top_site"/>
      <site rgba="0 0 0 0" size="0.005" pos="0.03 0.03 0" name="horizontal_radius_site"/>
    </body>
  </worldbody>
</mujoco>
```

**Comment by zhuyifengzju** [comment]
Hi,
    `composite` is supported by dm_control, but currently not supported by robosuite. An alternative in robosuite is to create a chain of capsules to simulate deformable objects, achieving similar behaviors as `composite`.
