### ISSUE TITLE
MuJoCo Menagerie

### ISSUE THREAD

**Issue by kevinzakka** [ARISE-Initiative/robosuite#381]
Hey folks,

Wondering how you feel about transitioning the robot models to the ones in [Menagerie](https://github.com/deepmind/mujoco_menagerie). We'll be sysID'ing them later this year so they will keep improving.

**Comment by snasiriany** [comment]
Hi Kevin, thanks for the suggestion! We haven't spoken as a team about this yet, here's my thoughts. If the Menagerie models are most realistic than the ones we have it'd be worth the transition. One potential challenge is maintaining backwards compatibility with our existing datasets (robomimic and other projects than use robosuite). So there's a tradeoff here. I'll let other team members add their thoughts as well.

**Comment by kevinzakka** [comment]
That makes sense, thanks @snasiriany!

**Comment by yukezhu** [comment]
Thanks @kevinzakka! Menagerie is a great effort and has been on our radar for a while. We decided not to migrate due to the backward compatibility issues Soroush mentioned earlier. But that's definite an option we should and will revisit for future robosuite releases.
