### ISSUE TITLE
Missing dependency in setup.py

### ISSUE THREAD

**Issue by wookayin** [ARISE-Initiative/robosuite#382]
It looks like h5py and termcolor are mandatory dependencies, but they are not included in setup.py so installing and importing `robosuite` will result in an `ImportError` of `h5py` and `termcolor`. As of v1.4 version installed through pypi.

**Comment by snasiriany** [comment]
Thanks for letting us know. `termcolor` is [already included](https://github.com/ARISE-Initiative/robosuite/blob/1b825f11a937f5c18f2ac167af8ab084275fc625/setup.py#L25) in setup.py and `h5py` can be setup by running `pip install -r requirements-extra.txt`.

**Comment by wookayin** [comment]
Hi, but the package doesn't work out of box because h5py is missing. Robosuite is supposed to be installed via pip, and these packages are **mandatory** (otherwise you cannot import the module) -- requirements.txt is not a valid, standard way of listing dependencies.

**Comment by snasiriany** [comment]
@wookayin thanks for following up. I'm don't think `h5py` in particular is mandatory to create environments and run them. Some scripts (mainly demos and data collection tools) require `h5py` but this is not something most users will need. Regarding requirement.txt being non-standard, I can run your concerns by my team, and if we decide to list everything in `setup.py` we will make the appropriate changes. Thanks!
