### ISSUE TITLE
How to get camera quat based on (camera_pos, lookat_dir, up) for mujoco renderer

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [ARISE-Initiative/robosuite#401]
How would you go from `(camera_pos, lookat, up)` to quat for the mujoco renderer (not e.g. nvsii) to set the camera pose?

My use case is that I want to initialize the cameras in a circle and point them all towards the center of the table; and it'd save a lot of time to not have to manually copy paste quat values from `tune_camera.py`. If anyone has pointers, that'd be much appreciated!

**Comment by SiyuanHuang95** [comment]
would like to know whether there is any update?
