### ISSUE TITLE
Support for Shadow Hand

### ISSUE THREAD

**Issue by nils-ingelhag** [ARISE-Initiative/robosuite#407]
Hi!

Is there any plan for adding support for the "Shadow Dexterous Hand"?

Best,
Nils

**Comment by zhuyifengzju** [comment]
Hi Nils,
     We curerntly do not have an immediate plan of implementation for adding dexterous hands. If you are in need of this gripper model, you could first try to add a shadow hand on your end by creating a new gripper file as the [panda hand](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/grippers/panda_gripper.py), and update the [registry of the gripper](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/models/grippers/__init__.py).

Let me know if you need help or any other questions.
