### ISSUE TITLE
Hi, 

### ISSUE THREAD

**Issue by rynem89** [ARISE-Initiative/robosuite#408]
Hi, i am trying to use robosuite on pycharm, and have an error of "No module named 'robosuite.macros_private' " while trying to import robosuite even after I installed it correctly. After tracing the error I found the the following ROBOSUITE_DEFAULT_LOGGER.warn("No private macro file found!")
    ROBOSUITE_DEFAULT_LOGGER.warn("It is recommended to use a private macro file")
    ROBOSUITE_DEFAULT_LOGGER.warn("To setup, run: python {}/scripts/setup_macros.py".format(robosuite.__path__[0])) but I don't know how to create a private macro

**Comment by snasiriany** [comment]
please run the following script from the base robosuite path:
`python robosuite/scripts/setup_macros.py`
