### ISSUE TITLE
Minor documentation issue

### ISSUE THREAD

**Issue by dwaitbhatt** [ARISE-Initiative/robosuite#413]
The docstring for _sample_quat() method in placement_samplers.py says that it returns euler angles, while it does in fact return a quaternion:
https://github.com/ARISE-Initiative/robosuite/blob/aeec87157dbde50bc8a746acde14a3b345a6213b/robosuite/utils/placement_samplers.py#L190C62-L190C62

**Comment by yukezhu** [comment]
@dwaitbhatt do you mind submitting a pull request to get this fixed?
