### ISSUE TITLE
Implementing trained agent to the real robot

### ISSUE THREAD

**Issue by Soha18** [ARISE-Initiative/robosuite#423]
Hi,

Thanks for opening this repository.

I'm trying to implement lift task on real Panda robot after training a model on the simulator (robosuite), and need to know for sure about the observations and actions coordinates in the simulator. (I'm using OSC-POSE controller)
- Are  'cube_pos', 'cube_quat' ,'eef_pos' and 'eef_quat' in the observations are in world frame? (when we get observations from observations = env.reset() for example)
- The output action vector contains delta position and delta axis angles, and it is used to calculate the target pose of the end-effector, do I need to get this resulting eef pose in base frame to feed it to the controller? or it is already in base frame?
- 
Please consider my query..
Thanks a lot and I appreciate any help

**Comment by zhuyifengzju** [comment]
Answer in issues #428
