### ISSUE TITLE
Horizontal robot arm or vacuum gripper

### ISSUE THREAD

**Issue by xieleo5** [ARISE-Initiative/robosuite#425]
I'm trying to create a Hanoi Tower env. I placed some pillars and disks on the table and found that most of the robot arm's fingers were not long enough to pick up the disk.
![screenshot](https://github.com/ARISE-Initiative/robosuite/assets/55373943/780425fd-9eea-43e9-8560-d4a9cb5873d3)
I'm currently thinking about two solutions. 
1. Initialize the robot arm in a horizontal way instead of a vertical way so that the arm can grab from the side.
2. Having a vacuum gripper that sucks objects. I found in [MuJoCo Doc](https://mujoco.readthedocs.io/en/latest/XMLreference.html#actuator-adhesion) that such a gripper is possible. I'm not sure of the difficulty of creating this.

I want to ask for some suggestions about which way to go.

**Comment by zhuyifengzju** [comment]
Hi,
We haven't implemented vacuum gripper, so we do not know if the gripper can fit into the current codebase. If you can implement a working one, then that would be great and we would be happy to take any PR from you.

As for gripper lengths, you can also try to replace the gripper model with other ones, such as the Robotiq grippers.
