### ISSUE TITLE
How to get joint angle in singlearm environment

### ISSUE THREAD

**Issue by lyuyiqi** [ARISE-Initiative/robosuite#427]
Hi, 
Could anyone tell me how to get the angles (qpos) of all the joints in a single or two arm environment? Thank you!

**Comment by zhuyifengzju** [comment]
Hi,
Here is what you need to do. First, activate the joint position observation in an inherited method `_setup_observables` in your custom implementation of an environment class.
```
observables = super()._setup_observables()

observables["robot0_joint_pos"]._active = True
 ```

And then when you obtain observation like this:
```
obs, _, _, _ = env.step(action)
```
You can retrieve the joints at each timestep. If it's a two-arm environment, then you need to query the joint position with the correct naming.
