### ISSUE TITLE
Interacting with Environment in mujoco viewer

### ISSUE THREAD

**Issue by Aditya-1729** [ARISE-Initiative/robosuite#430]
Is there a possibility of opening an interactive instance of the environment on mujoco viewer? 
I have made a custom environment, similar to Wipe where I am trying to tweak the dynamic parameters of end effector the surface it sweeps.  I feel interactive sessions can be incredibly useful in such a setting of trial and error with parameters.

**Comment by snasiriany** [comment]
We're working on this feature, and we aim to ship this in the next release of robosuite!

**Comment by zhuyifengzju** [comment]
Closing this issue and will reopen when we introduce the new feature.

**Comment by benediktkreis** [comment]
Did you introduce this new feature?
