### ISSUE TITLE
Robosuite for mujoco 3.0

### ISSUE THREAD

**Issue by MichalMotak** [ARISE-Initiative/robosuite#433]
Hi, does robosuite works with mujoco 3.0? If not, do you plan to release a new version of robosuite with mujoco 3.0 support? 
Thanks for your answer.

**Comment by jsalfity** [comment]
I just installed mujoco 3.0 and robosuite worked for me. I'm on macOS.

**Comment by snasiriany** [comment]
It should work with mujoco 3.0. However, we haven't extensively tested with 3.0 yet. We plan to update the recommended version of mujoco in the future.
