### ISSUE TITLE
About rotation and self.reference_target_orn

### ISSUE THREAD

**Issue by Xianqi-Zhang** [ARISE-Initiative/robosuite#436]
Hi,
Thanks for your sharing.
I have a question about rotation.
In controllers.ik.py Line-393
```python
# Update reference target orientation
self.reference_target_orn = T.quat_multiply(self.reference_target_orn, base_orn_in_world)
```
I am very confused about the fact that `self.reference_target_orn` needs to be continuously multiplied by `base_orn_in_world` and then saved, what is the purpose of doing this? 
And the quaternions here do not use $qpq^{-1}$ to calculate rotation as written in many tutorials, why is this? 
Is there any book or tutorial that I can refer to?

Thank you for your any reply.

Best regards.

**Comment by kevin-thankyou-lin** [comment]
Apologies for the lack of response --- we'll be having a new IK controller based on Kevin Zakka's [mjctrl](https://github.com/kevinzakka/mjctrl) coming soon. This version uses pybullet and has some non-intuitive coordinate transforms to get things working.
