### ISSUE TITLE
Joint position controller sim2real for franka panda

### ISSUE THREAD

**Issue by 304x** [ARISE-Initiative/robosuite#442]
Hi,
I am trying to implement the robosuite joint position controller for a real franka panda robot and I observe a very strange behavior: the lower three joints (0-2)  seem to work normal  but the upper four joints (3-6) wont move at all. Has someone experienced the same problem and maybe has some advice or even an working example in cpp?

**Comment by zhuyifengzju** [comment]
Hope [this](https://github.com/UT-Austin-RPL/deoxys_control/blob/main/deoxys/franka-interface/src/controllers/joint_impedance.cpp) helps.
