### ISSUE TITLE
Remove Aligning tool when collecting demonstrations

### ISSUE THREAD

**Issue by Dhanushvarma** [ARISE-Initiative/robosuite#452]
Can you please help, on we can toggle of this visualization when collecting the demos. The green "alignment line through the gripper".

![image](https://github.com/ARISE-Initiative/robosuite/assets/43350818/58b6ea7e-f9f8-4f29-ba86-113ba88ab45c)

**Comment by zhuyifengzju** [comment]
Hi, I believe you want to modify or remove the [visualization wrapper](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/wrappers/visualization_wrapper.py) to toggle this off. Please let me know if this is what you want.
