### ISSUE TITLE
Release v1.4.1?

### ISSUE THREAD

**Issue by manuelhaussmann** [ARISE-Initiative/robosuite#453]
Hi, 

pip only has access to v1.4 and it is also the only one that is listed here in the releases. Are there any plans for v1.4.1? That branch includes the important logging fix (https://github.com/ARISE-Initiative/robosuite/pull/391).

**Comment by yukezhu** [comment]
Thanks for the reminder. We will update the pip release versions in this week.

**Comment by yukezhu** [comment]
This has been updated. Thanks again for the reminder.
