### ISSUE TITLE
How can I use mujoco GUI to visualize?

### ISSUE THREAD

**Issue by DDDog-WANG** [ARISE-Initiative/robosuite#456]
If robosuite.env.render is based the camera in mujoco simulation, how can I render by mujoco directly? (I want to see 3D view)

**Comment by zhuyifengzju** [comment]
Hi, we are currently putting up a pull request for robosuite users to access the mjviewer. Please stay tuned. It will be online in a few days.

**Comment by kevin-thankyou-lin** [comment]
@zhuyifengzju did we make the PR? If so, we can close this issue

**Comment by kevin-thankyou-lin** [comment]
If it's not already in there, we'll have mjviewer as the default renderer for our next release
