### ISSUE TITLE
How add an impedance controller in teleoperation

### ISSUE THREAD

**Issue by 206333308** [ARISE-Initiative/robosuite#465]
I now have a haptic device called omega7 ( As shown below ), and I have written its device file. Now I use it for teleoperation to operate the ur5e robotic arm in the simulation. I now want to add an impedance controller and use this controller to achieve better teleoperation. Where should I start to modify it. Thank you for your generous help

**Comment by Jericho-Ma** [comment]
![Uploading omega6v.jpg…]()

**Comment by Jericho-Ma** [comment]
![omega6v](https://github.com/ARISE-Initiative/robosuite/assets/157143406/23a424ea-96a4-4e9a-b724-a3e126896e09)

**Comment by kevin-thankyou-lin** [comment]
So you've written the device according to [these docs](https://robosuite.ai/docs/simulation/device.html) and want to use an impedance controller? I'd create a file on the same level as the [osc controller](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/controllers/osc.py) and inherit from the `controller` class. E.g.:

```from robosuite.controllers.base_controller import Controller

class ImpedanceController:
     ...
```
