### ISSUE TITLE
Add custom env to robosuite.make

### ISSUE THREAD

**Issue by bhe1004** [ARISE-Initiative/robosuite#468]
How can I create a custom env through robosuite.make? I have created a single_arm_peg_in_hole env like the format of the env python files in robosuite's environments/minipulatation, but I don't know how to apply it to robosuite.make().

**Comment by zhuyifengzju** [comment]
Hi, if you want robosuite.make() to find it, you would need to import your custom env before  (`ALL_ENVIRONMENTS`)[https://github.com/ARISE-Initiative/robosuite/blob/eafb81f54ffc104f905ee48a16bb15f059176ad3/robosuite/environments/__init__.py#L3] is set. Look into this variable to see if your custom environment is set.
