### ISSUE TITLE
Confusion about the action space of the controller

### ISSUE THREAD

**Issue by Victeldo** [ARISE-Initiative/robosuite#474]
Hi,

I'm currently using Robosuite for the simulation environment to train a policy for the Kinova gen 3 arm, as part of my Probabilistic Robotics final project. I'm planning on using the trained policy on the real robot; however, I was facing difficulties in understanding the action space of the robot.  

In the Robosuite environment, it appears that the actions are in terms of an array of joint (and gripper) velocities with a range of [-1,1] each. However, I'm a little unsure if I'm to interpret it as a percent of the max RPM of the joint, or if I'm meant to interpret it another way. If it does mean joint velocities, what is the expected duration of each action?  Additionally, is there any way to get actions in terms of joint positions instead? 

Thanks,
Prithvi

**Comment by zhuyifengzju** [comment]
Hi，
In robosuite you can specify the controller to be [joint position](https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/controllers/joint_pos.py). I am not sure why you would need to condition on max RPM. Whether joint positions or velocities should be based on the unit of rad or rad/s. THe duration of each action is typically the loop of `env.step` you invoke, so you would need to write your own logic to achieve some closed-loop behavior.
