### ISSUE TITLE
Specific type of Position controller for robosuite/robomimic

### ISSUE THREAD

**Issue by palashag12** [ARISE-Initiative/robosuite#480]
Hi
I am working with waypoint based method for imitation learning and need a specific type of controller that is given a fixed amount of time to reach a specified position. Hoever if it reaches the position earlier than this fixed amount of time, the controller should terminate. Is there any such controller in robosuite?

**Comment by kevin-thankyou-lin** [comment]
Unfortunately not: you'll probably need to implement something in your policy eval script that specifically checks stores the current amount of 'time' elapsed (probably something like simulator time) to see if the arm/hand has reached the position, then query for the next action if so
