### ISSUE TITLE
Image based RL for Robosuite 

### ISSUE THREAD

**Issue by lakshitadodeja** [ARISE-Initiative/robosuite#483]
Hi ! 
I was wondering if there are any repos that do Image-based online RL for robosuite. I saw the robosuite-benchmark repo and it seems to be using the low level dimensions for objects directly.

**Comment by kevin-thankyou-lin** [comment]
@snasiriany @amandlek do we have image based RL somewhere for robosuite?

**Comment by allenzren** [comment]
We have image based online PPO-like RL set up for Can/Lift/Square/Transport with [DPPO](https://github.com/irom-lab/dppo). I think [IBRL](https://github.com/hengyuan-hu/ibrl) has Can/Square set up with Q-learning.

**Comment by kevin-thankyou-lin** [comment]
Amazing; thanks for sharing these, Allen! I'll pin this issue. Congrats on the awesome work :)
