### ISSUE TITLE
Issue about install robosuite

### ISSUE THREAD

**Issue by Yingfan99327** [ARISE-Initiative/robosuite#485]
Hi,

May I ask a problem about installing robosuite via the installation guidelines provided in the project webpage like pip install robosuite. I met some problems with errors as follows,

he 'linux/input.h' and 'linux/input-event-codes.h' include files
      are missing. You will have to install the kernel header files in
      order to continue:
      
          dnf install kernel-headers-$(uname -r)
          apt-get install linux-headers-$(uname -r)
          emerge sys-kernel/linux-headers
          pacman -S kernel-headers
      
      In case they are installed in a non-standard location, you may use
      the '--evdev-headers' option to specify one or more colon-separated
      paths. For example:
      
          python setup.py \
            build \
            build_ecodes --evdev-headers path/input.h:path/input-event-codes.h \
            build_ext --include-dirs path/ \
            install
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for evdev
Failed to build evdev
ERROR: Could not build wheels for evdev, which is required to install pyproject.toml-based projects

I tried some methods, but they didn't work. It would be great if you could offer me any help, thank you very much.

**Comment by yl-wang996** [comment]
This is because the corresponding wheel of the python is not exist, then the installer trying to build it.

Two solutions:
1. change your python version to which the prebuilt wheel file existed.
2. refer to this [link](https://github.com/onnx/onnx/issues/4376#issuecomment-1236614971) to install the dependencies for building the wheel.
