### ISSUE TITLE
Confusing about the Quaternion is (x,y,z,w) or (w,x,y,z)

### ISSUE THREAD

**Issue by super-dashuaibi** [ARISE-Initiative/robosuite#488]
Hi, I'm confused about the definition of Quaternion.
when i read the doc of mujoco ( https://mujoco.readthedocs.io/en/stable/modeling.html#corientation), which says:
     quat: real(4), “1 0 0 0”
     If the quaternion is known, this is the preferred was to specify the frame orientation because it does not involve conversions. Instead it is normalized to unit length and copied into mjModel during compilation. When a model is saved as MJCF, all frame orientations are expressed as quaternions using this attribute.

And it seems to be  (w,x,y,z)
but when i read the transform_utils.py (../robosuite/robosuite/utils/transform_utils.py),which says :
      @jit_decorator
      def mat2quat(rmat):
          """
          Converts given rotation matrix to quaternion.
      
          Args:
              rmat (np.array): 3x3 rotation matrix
      
          Returns:
              np.array: (x,y,z,w) float quaternion angles
          """
And it seems to be (x,y,z,w).
In a word, I don't know which definition I should use

**Comment by amandlek** [comment]
Most of the operations we do on quaternions in this codebase assume xyzw, but when reading quaternions directly from mujoco, they are wxyz. This is why we readily convert between the two formats (e.g. see [here](https://github.com/ARISE-Initiative/robosuite/blob/eafb81f54ffc104f905ee48a16bb15f059176ad3/robosuite/environments/manipulation/lift.py#L362)). I would suggest sticking with xyzw, and remembering to do the conversion anytime you read quaternions directly from mujoco.
