### ISSUE TITLE
Fail to render: sawyer robot has blank screen

### ISSUE THREAD

**Issue by spacegoing** [ARISE-Initiative/robosuite#491]
I had a fresh install of this repo and tried rendering Sawyer robot with:

https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/demos/demo_renderers.py
and
https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/demos/demo_video_recording.py

All these scripts failed to render sawyer robot.

I tried 
https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/demos/demo_renderers.py
and
https://github.com/ARISE-Initiative/robosuite/blob/master/robosuite/demos/demo_video_recording.py
with the other robots. All robots and scenes work, except for Sawyer robot didn't work for any scenes.

**Comment by kevin-thankyou-lin** [comment]
Thanks for bringing this up! Resolved in [v1.5](https://github.com/ARISE-Initiative/robosuite/tree/v1.5.0) [push coming to master branch soon]
