### ISSUE TITLE
Could not find module ..\robosuite\utils\mujoco.dll

### ISSUE THREAD

**Issue by MinnaZhong** [ARISE-Initiative/robosuite#496]
Hey guys,

I am trying to use Robocasa, it requires installing Robosuite lib first.

When I run **python robocasa/scripts/setup_macros.py** , mujoco.dll could not be found.
![image](https://github.com/user-attachments/assets/dfc9841f-4083-4ed0-8ca0-1f6473b6df05)

There is no error when installing robosuite, but when I use **python -m robosuite.demos.demo_random_action** to verify it, it shows mujoco.dll could not be found again.
![image](https://github.com/user-attachments/assets/9e1312eb-01e4-4ad2-a203-4f147cb73798)
![image](https://github.com/user-attachments/assets/3016af93-24c7-4e12-81e3-7c2229e55322)

What should I do? Thanks,

Minna

**Comment by abhihjoshi** [comment]
Are you using a Windows machine? If so, please refer to this solution here as it could be helpful: https://github.com/ARISE-Initiative/robosuite/issues/323#issuecomment-1707864112

**Comment by MinnaZhong** [comment]
Hi, I am using Win10 and python3.9, I can't find mujoco folder under my env project, would you please share the mujoco.dll with me?

**Comment by abhihjoshi** [comment]
Have you pip installed mujoco? I would recommend running the command `pip install mujoco=3.1.1`. The mujoco.dll file should be present after you do this.

**Comment by briliantnugraha** [comment]
> Have you pip installed mujoco? I would recommend running the command `pip install mujoco=3.1.1`. The mujoco.dll file should be present after you do this.

Unfortunately, for me, doing pip install alone won't copy the .dll file to robosuite folder. To solve this issue, I copy the mujoco.dll from ```mujoco/``` folder in **site-packages** to ```robosuite/utils/```. Hope it helps others, cheers~
