### ISSUE TITLE
A small question about the difference between the way of decomposing and composing different models in Mujoco applied in robosuite and that realized in pyMJCF

### ISSUE THREAD

**Issue by Yingfan99327** [ARISE-Initiative/robosuite#508]
Hi,

I hope you're enjoying a nice day today!

I just have a small question regarding the difference between the way of decomposing and composing different models in Mujoco applied in robosuite and that realized in pyMJCF. I think robosuite provides a very powerful tool to manipulate MJCF xml models and I guess the code parts are in mjcf_utils.py, right? And recently, I just found that dm_control also provides such a pylib called pyMJCF which could also be used in manipulating the MJCF xml model files. I am just curious about the difference between your method and this lib? Do they basically have the same function? Could you give me some tips on the advantages and disadvantages of these two implementation?

Thanks very much and wishing you all the best.

**Comment by kevin-thankyou-lin** [comment]
From my understanding, pyMJCF is a DeepMind-native package; `mjcf_utils.py` has very similar functionality but is more specific to robosuite; so if you're using robosuite, maybe use `mjcf_utils.py`, but if you use `dm_control` or mujoco more generally, perhaps use pyMJCF.
