### ISSUE TITLE
problem to run quick start

### ISSUE THREAD

**Issue by Moj79a** [ARISE-Initiative/robosuite#512]
hello I have a problem running this file.
![image](https://github.com/user-attachments/assets/9d89d08e-f0e4-4d89-a7e8-3d9cd1e36d19)
 I received the following error :
Exception has occurred: AttributeError
module 'robosuite' has no attribute 'make'
File "C:\Users\Mojtaba\Desktop\nhj.py", line 5, in
env = suite.make(
^^^^^^^^^^
AttributeError: module 'robosuite' has no attribute 'make'

**Comment by kevin-thankyou-lin** [comment]
Did you follow the steps in [intsallation](https://robosuite.ai/docs/installation.html)?

And, are you running the script inside a conda env w/ robosuite installed?

**Comment by Moj79a** [comment]
yes. i follow the steps in installation.
yes

**Comment by zhuyifengzju** [comment]
Can you first try to remove / uninstall and reinstall again using `pip install -e .`? It's highly recommended to install it from source if pip install doesn't work well. Also, sometimes the virtual environment might screw up things and have some fake "robosuite" pointer where nothing is really there. So it's good to reinstall everything, just to make sure any previous installation is not messing up.

**Comment by kevin-thankyou-lin** [comment]
closing for now, feel free to re-open
