### ISSUE TITLE
Is it possible to get additional values from the objects in the scene?

### ISSUE THREAD

**Issue by gadorneles** [ARISE-Initiative/robosuite#523]
I saw it's possible to obtain the position and orientation of an object using obs['obj_pos'], for example. However, I would like to expand that and get values I could only obtain with access to the mesh. For example, the specific position of a handle in a mug or a cap in a bottle. Is there a way this can be done? Would I need to calculate individually based on every mesh and its position?

**Comment by kevin-thankyou-lin** [comment]
If it's specific to the object mesh, you'll need to do the computation directly on the mesh itself.
You can add an object sensor e.g. [here](https://github.com/ARISE-Initiative/robosuite/blob/74981fd347660205efb4f8c0005e28ec621f5304/robosuite/environments/manipulation/tool_hang.py#L532) and create a new sensor
