### ISSUE TITLE
The SingleArmEnv just vanished in transition from 1.4 to 1.5?

### ISSUE THREAD

**Issue by AtharvanDogra** [ARISE-Initiative/robosuite#560]
### System Info

```Shell
Robosuite – 1.5
```

### Information

Have the functions of SingleArmEnv been ported to some other module or is it just a bug?

### Reproduction

from robosuite.environments.manipulation.single_arm_env import SingleArmEnv

**Comment by snasiriany** [comment]
Yes, it has been removed! Before, environments were restricted to only working with single arm robots or two arm robots. Now any kind of robot can be used in (almost) all environments. Hence, we no longer need the distinction of using SingleArmEnv.
