### ISSUE TITLE
Reward modification to stabilize robot

### ISSUE THREAD

**Issue by garg-akash** [ARISE-Initiative/robosuite#563]
Hello,

Firstly, thank you for providing such an interesting framework. 

As I trained a DDPG policy on a Universal Robots model for cube lifting task using dense reward, I noticed that although the robot can pick the cube but it's quite unstable at times (jerk, oscillations etc.). It is most likely due to the fact that the reward function only considers if the robot is approaching the cube and if the cube has been lifted above the tabletop. 

Is it a good idea to formulate a custom reward function that penalizes, for example, large robot joint velocity changes? Am I missing something about the environment here?

Thank you for the support in advance!
Akash

**Comment by kevin-thankyou-lin** [comment]
Sure! Which controller are you using --- is it the OSC controller? Yes - you can certainly try adding extra reward terms in a custom reward function.

**Comment by garg-akash** [comment]
Thank you for the prompt reply.

Yes, I'm using OSC controller at the moment.

**Comment by kevin-thankyou-lin** [comment]
Gotcha, yeah adding some extra reward term would make sense
