### ISSUE TITLE
About the movement of objects in the simulation environment

### ISSUE THREAD

**Issue by hahahalove57** [ARISE-Initiative/robosuite#564]
Hello, thank you for your excellent contribution！ I noticed that def clear_objects(self, object_names) in robosuite can modify the position or state of the relevant object without using env.step to control the robot colliding with object  to change its position state. Is there any related function to directly control the object state in the simulation without the robot? If not, how to write the related function? That is, modify the relevant data in the sim

**Comment by kevin-thankyou-lin** [comment]
For sure! 

What part of `clear_objects` doesn't work?

```python
    def clear_objects(self, object_names):
        """
        Clears objects with the name @object_names out of the task space. This is useful
        for supporting task modes with single types of objects, as in
        @self.single_object_mode without changing the model definition.
        Args:
            object_names (str or list of str): Name of object(s) to remove from the task workspace
        """
        object_names = {object_names} if type(object_names) is str else set(object_names)
        for obj in self.model.mujoco_objects:
            if obj.name in object_names:
                self.sim.data.set_joint_qpos(obj.joints[0], np.array((10, 10, 10, 1, 0, 0, 0)))
```

the key line is `self.sim.data.set_joint_qpos(obj.joints[0], np.array((10, 10, 10, 1, 0, 0, 0)))`
