### ISSUE TITLE
MuJoCo viewer to Fullscreen by default

### ISSUE THREAD

**Issue by Dhanushvarma** [ARISE-Initiative/robosuite#580]
Hello,

I am trying to use the robosuite repositry to collect demonstrations, is there anyway to make the `MuJoCo` UI screen (`MjviewerRenderer`) to render in full-screen by default, as this required for the application I am working on.

Any help or suggestions would be greatly appreciated.

**Comment by Abhiram824** [comment]
Hello, I believe the `f5` key is a shortcut to putting the UI in fullscreen. It might be possible to automatically register a keypress when the viewer is launched. However, I don't think it is possible to directly configure the MjViewerRenderer to default to full screen.
