### ISSUE TITLE
question about rendering

### ISSUE THREAD

**Issue by tobottyx** [ARISE-Initiative/robosuite#595]
### System Info

```Shell
ubuntu20.04 robosuite 1.5
```

### Information

Below is my code, a simple example, but I found that when a round ends and I reset the environment, the rendering will stop. How can I solve this problem?

```

from robosuite.models import MujocoWorldBase
from robosuite.models.arenas import TableArena
from robosuite.models.grippers import gripper_factory
from robosuite.models.robots import UR5e
from robosuite.wrappers import GymWrapper
from robosuite.utils.input_utils import *
from robosuite.controllers import load_part_controller_config
import numpy as np
if __name__ == '__main__':
    MAX_FR = 25 
    gripper = gripper_factory('InspireRightHand')
    env = suite.make("Lift",
                    robots=["UR5e"],  
                    gripper_types="InspireRightHand", 
                    env_configuration="opposed",
                    has_renderer=True, 
                    has_offscreen_renderer= False,
                    render_camera="frontview",  
                    control_freq=20, 
                    horizon=200,  
                    use_object_obs=False,  
                    use_camera_obs=False)  
    # process(env)
    env.reset()
    for i in range(1000):
        action = np.random.randn(*env.action_spec[0].shape) * 0.1
        obs, reward, done, info = env.step(action)  # take action in the environment
        if done:
            env.reset()
        env.render()  # render on display
```

    
    

### Reproduction

I want the rendering to reset as well

**Comment by tobottyx** [comment]
> ### 系统信息
> ```shell
> ubuntu20.04 robosuite 1.5
> ```
> 
> ### 信息
> 下面是我的代码，一个简单的例子，但我发现当一轮结束并且我重置环境时，渲染就会停止。我该如何解决这个问题？
> 
> ```
> 
> from robosuite.models import MujocoWorldBase
> from robosuite.models.arenas import TableArena
> from robosuite.models.grippers import gripper_factory
> from robosuite.models.robots import UR5e
> from robosuite.wrappers import GymWrapper
> from robosuite.utils.input_utils import *
> from robosuite.controllers import load_part_controller_config
> import numpy as np
> if __name__ == '__main__':
>     MAX_FR = 25 
>     gripper = gripper_factory('InspireRightHand')
>     env = suite.make("Lift",
>                     robots=["UR5e"],  
>                     gripper_types="InspireRightHand", 
>                     env_configuration="opposed",
>                     has_renderer=True, 
>                     has_offscreen_renderer= False,
>                     render_camera="frontview",  
>                     control_freq=20, 
>                     horizon=200,  
>                     use_object_obs=False,  
>                     use_camera_obs=False)  
>     # process(env)
>     env.reset()
>     for i in range(1000):
>         action = np.random.randn(*env.action_spec[0].shape) * 0.1
>         obs, reward, done, info = env.step(action)  # take action in the environment
>         if done:
>             env.reset()
>         env.render()  # render on display
> ```
> 
> ### 生殖
> 我也希望重置渲染
> 
> ### 预期行为
> _没有回应_
![2024-12-18 17-09-22 的屏幕截图](https://github.com/user-attachments/assets/93a2224e-b0b5-4c4a-a114-e19cd91753a0)

**Comment by abhihjoshi** [comment]
Thanks for bringing this up! I think this may be an issue with the reset function in the MjViewer renderer. If possible, could you try to change the `reset` function in `robosuite/renderers/mjviewer/mjviewer_renderer.py` to:
```
def reset(self):
    self.close()
    self.update()
```
Please let me know if this works for you. If you pip installed robosuite, you may have to change the code in site-packages (not the ideal fix, just temporary). Will hopefully try to create a PR for this to fix this issue.

**Comment by tobottyx** [comment]
I'll try. Thanks

**Comment by snasiriany** [comment]
Hi @tobottyx as of very recently this issue should be fixed. Please pull the latest from `master` branch
